"""Tests for `palaver.extract.normalize` — JSONL to semantic turn stream.

Every fixture built inline here is invented for this test (INV-9): no real
`~/.claude/` session store is ever opened, globbed, or read, and no prose in
this module was copied, sampled, or paraphrased from a real agent session.
The one *committed* fixture this module reads,
`tests/fixtures/compaction-boundary.jsonl`, was produced sanitized by task
1.7 and is exactly the source of `tests/fixtures/golden/compaction-boundary.normalized.txt`
below — nothing in the golden file is prose this module introduced.

**Why `test_injected_content_is_tagged_as_injected` is named exactly that.**
It was renamed 2026-08-14 from `test_injected_content_is_not_tier_one`, which
is now INV-8's charter `gate_test` name and belongs to task 3.3
(`tests/test_extraction.py`), where a write boundary actually exists to
reject a tier. This module has no tier and rejects nothing; it classifies
and tags. Carrying the old name here would make the charter's rejection
property read as covered when nothing in this file checks it.
"""

from __future__ import annotations

import ast
import json
import logging
from pathlib import Path

from palaver.extract.normalize import normalize_path, normalize_records
from palaver.ingest.adapters.claude_code import SYSTEM_SUBTYPE_KINDS

REPO_ROOT = Path(__file__).resolve().parent.parent
NORMALIZE_MODULE_PATH = REPO_ROOT / "palaver" / "extract" / "normalize.py"
GOLDEN_PATH = REPO_ROOT / "tests" / "fixtures" / "golden" / "compaction-boundary.normalized.txt"
COMPACTION_FIXTURE_PATH = REPO_ROOT / "tests" / "fixtures" / "compaction-boundary.jsonl"


# --- record builders (invented content only, INV-9) -------------------------


def _user_record(text: str, *, is_meta: bool = False, session_id: str = "fixture-synth") -> dict:
    return {
        "type": "user",
        "sessionId": session_id,
        "isMeta": is_meta,
        "message": {"role": "user", "content": [{"type": "text", "text": text}]},
    }


def _assistant_text_record(text: str, *, session_id: str = "fixture-synth") -> dict:
    return {
        "type": "assistant",
        "sessionId": session_id,
        "message": {"role": "assistant", "content": [{"type": "text", "text": text}]},
    }


def _tool_use_record(name: str, tool_input: dict, *, session_id: str = "fixture-synth") -> dict:
    return {
        "type": "assistant",
        "sessionId": session_id,
        "message": {
            "role": "assistant",
            "content": [{"type": "tool_use", "id": "tu-1", "name": name, "input": tool_input}],
        },
    }


def _tool_result_record(*, is_error: bool, content: str, session_id: str = "fixture-synth") -> dict:
    return {
        "type": "user",
        "sessionId": session_id,
        "isMeta": False,
        "message": {
            "role": "user",
            "content": [
                {
                    "type": "tool_result",
                    "tool_use_id": "tu-1",
                    "is_error": is_error,
                    "content": content,
                }
            ],
        },
    }


def _line(record: dict) -> bytes:
    return (json.dumps(record) + "\n").encode("utf-8")


def _write_jsonl(path: Path, items: list) -> None:
    """Write a JSONL fixture. A `bytes` item is written verbatim (corrupt lines)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(b"".join(item if isinstance(item, bytes) else _line(item) for item in items))


def _lines_containing(output: str, needle: str) -> list[str]:
    return [line for line in output.splitlines() if needle in line]


# =============================================================================
# Golden file: normalize(compaction-boundary.jsonl) == committed golden text
# =============================================================================


def test_golden_compaction_boundary_matches_committed_fixture():
    """`normalize_path` on the committed fixture reproduces the reviewed golden file byte-for-byte.

    The golden file was generated by this implementation and then read back
    line by line against the raw fixture records before being committed —
    see the task report for the per-line check. This test's job is only to
    catch drift afterward, not to establish correctness on its own.
    """
    assert COMPACTION_FIXTURE_PATH.exists()
    normalized = normalize_path(COMPACTION_FIXTURE_PATH)
    golden = GOLDEN_PATH.read_text(encoding="utf-8")
    assert normalized == golden


def test_golden_fixture_channel_tags_match_the_raw_records():
    """Independent re-derivation: each golden line's tag matches what the raw record says.

    Re-reads `compaction-boundary.jsonl` itself (not through the normalizer)
    and checks each `user` record's `isMeta`/text against the tag the golden
    file carries for it, so this does not just re-assert the normalizer
    agrees with itself.
    """
    raw_lines = [json.loads(line) for line in COMPACTION_FIXTURE_PATH.read_text().splitlines()]
    user_records = [r for r in raw_lines if r["type"] == "user"]
    assert len(user_records) == 2
    for record in user_records:
        assert record["isMeta"] is False  # both are genuinely human-authored
    golden_lines = GOLDEN_PATH.read_text(encoding="utf-8").splitlines()
    human_lines = _lines_containing("\n".join(golden_lines), "HUMAN:")
    assert len(human_lines) == 2
    assert _lines_containing("\n".join(golden_lines), "INJECTED:") == []


# =============================================================================
# Size bound: ~900 KB JSONL normalizes to well under 60 KB
# =============================================================================


def _synthetic_session_records(min_raw_bytes: int) -> list[dict]:
    """Build corpus-shaped records (human ask, tool call, large tool output,
    agent summary) repeated until the JSONL encoding exceeds `min_raw_bytes`.

    Shaped after real session traffic: a short human/agent turn either side
    of a tool call whose output dominates the record's raw size — the same
    profile the spike measured 900 KB -> ~47 KB against. Nothing here is
    real corpus text; every string is templated and invented for this test.
    """
    tool_cycle = ("Bash", "Edit", "Grep")
    records: list[dict] = []
    raw_bytes = 0
    i = 0
    while raw_bytes < min_raw_bytes:
        tool = tool_cycle[i % len(tool_cycle)]
        if tool == "Bash":
            tool_input = {"command": (f"run_the_build_step --target service-{i}\n") * 60}
        elif tool == "Edit":
            tool_input = {
                "file_path": f"/repo/src/module_{i}.py",
                "old_string": "x" * 300,
                "new_string": "y" * 300,
            }
        else:
            tool_input = {"pattern": f"TODO_{i}"}

        unit = [
            _user_record(
                f"please look into issue number {i} and fix the underlying cause of the failure",
                session_id="fixture-synth",
            ),
            {
                "type": "assistant",
                "sessionId": "fixture-synth",
                "message": {
                    "role": "assistant",
                    "content": [
                        {"type": "thinking", "thinking": "reasoning about the fix in detail " * 80},
                        {"type": "tool_use", "id": f"tu-{i}", "name": tool, "input": tool_input},
                    ],
                },
            },
            _tool_result_record(
                is_error=False,
                content=(
                    f"build output line {i} with some detail about what happened during this step\n"
                )
                * 400,
                session_id="fixture-synth",
            ),
            _assistant_text_record(
                f"fixed issue {i}, the tests now pass and behavior matches the ticket "
                "description precisely",
                session_id="fixture-synth",
            ),
        ]
        for record in unit:
            raw_bytes += len(json.dumps(record)) + 1
        records.extend(unit)
        i += 1
    return records


def test_synthesized_900kb_input_normalizes_under_60kb(tmp_path):
    """A ~900 KB synthesized JSONL session normalizes to well under 60 KB.

    The input is built programmatically by `_synthetic_session_records`,
    never read from a committed blob, and written to a real file so this
    exercises `normalize_path`'s read path (`read_complete_records` /
    `open_source_readonly`), not just in-memory record handling.
    """
    records = _synthetic_session_records(900_000)
    path = tmp_path / "synthetic-session.jsonl"
    _write_jsonl(path, records)

    raw_size = path.stat().st_size
    assert raw_size >= 900_000  # the input really is ~900 KB, not a token gesture at it

    normalized = normalize_path(path)
    normalized_size = len(normalized.encode("utf-8"))

    assert normalized_size < 60_000
    # Not just "under the bound" by luck: the reduction is the point.
    assert normalized_size < raw_size / 10


# =============================================================================
# Channel tagging: INV-8's classification, not text sniffing
# =============================================================================


def test_injected_content_is_tagged_as_injected():
    """An `isMeta: true` record's line carries the injected tag and no human tag,
    with a genuinely human-authored record in the same input carrying the human tag.

    The positive control is not a separate test: without the human-channel
    record in this same input, a normalizer that emits nothing at all (or
    that emits no `HUMAN:` line ever) would still pass "no human tag on the
    injected line" vacuously. Requiring the human line to appear rules that
    out.
    """
    records = [
        _user_record(
            "<system-reminder>invented harness reminder text for this test</system-reminder>",
            is_meta=True,
        ),
        _user_record("please summarize the invented ticket for this test"),
    ]

    output = normalize_records(records)

    injected_lines = _lines_containing(output, "invented harness reminder text")
    assert len(injected_lines) == 1
    assert "INJECTED:" in injected_lines[0]
    assert "HUMAN:" not in injected_lines[0]

    # Positive control: the human-authored record in the same input.
    human_lines = _lines_containing(output, "invented ticket")
    assert len(human_lines) == 1
    assert "HUMAN:" in human_lines[0]
    assert "INJECTED:" not in human_lines[0]


def test_injected_prefix_without_ismeta_is_tagged_as_injected():
    """INV-8's second signal: a non-`isMeta` record still tags injected by text prefix.

    `isMeta: false` deliberately, so `classify_channel` cannot short-circuit
    on the structural flag — this exercises the prefix-table branch
    specifically. Paired with the same positive control pattern as above.
    """
    records = [
        _user_record("<command-name>/invented-status</command-name>", is_meta=False),
        _user_record("please check the invented deploy for this test"),
    ]

    output = normalize_records(records)

    injected_lines = _lines_containing(output, "invented-status")
    assert len(injected_lines) == 1
    assert "INJECTED:" in injected_lines[0]
    assert "HUMAN:" not in injected_lines[0]

    human_lines = _lines_containing(output, "invented deploy")
    assert len(human_lines) == 1
    assert "HUMAN:" in human_lines[0]


# =============================================================================
# Structural rendering: tool calls, tool results, thinking, system records
# =============================================================================


def test_tool_use_and_tool_result_carry_no_channel_tag():
    """Tool calls and tool outcomes are structural lines, never HUMAN/INJECTED/AGENT.

    A tool result is something that happened, not something said, so it has
    no channel; a `tool_use` block belongs to an `AGENT` record but is
    rendered on its own `tool>` line rather than folded into the `AGENT:`
    text line, so a reader (or a downstream quote-grounding gate) cannot
    mistake a rendered command for something the agent said in prose.
    """
    records = [
        _tool_use_record("Bash", {"command": "invented-command --for-this-test"}),
        _tool_result_record(is_error=False, content="invented tool output for this test"),
    ]

    output = normalize_records(records)

    tool_lines = _lines_containing(output, "invented-command")
    assert len(tool_lines) == 1
    assert "tool>" in tool_lines[0]
    for tag in ("HUMAN:", "INJECTED:", "AGENT:"):
        assert tag not in tool_lines[0]

    result_lines = _lines_containing(output, "invented tool output")
    assert len(result_lines) == 1
    assert "result>" in result_lines[0]
    for tag in ("HUMAN:", "INJECTED:", "AGENT:"):
        assert tag not in result_lines[0]


def test_tool_result_error_is_marked_distinctly_from_success():
    """`is_error: true` renders `result[error]>`; `is_error: false` renders plain `result>`.

    The success case is the positive control: without it, a normalizer that
    always emitted `result[error]>` regardless of `is_error` would still
    pass a lone "error is marked" assertion.
    """
    records = [
        _tool_result_record(is_error=True, content="invented failure output for this test"),
        _tool_result_record(is_error=False, content="invented success output for this test"),
    ]

    output = normalize_records(records)

    error_lines = _lines_containing(output, "invented failure output")
    assert len(error_lines) == 1
    assert "result[error]>" in error_lines[0]

    success_lines = _lines_containing(output, "invented success output")
    assert len(success_lines) == 1
    assert "result>" in success_lines[0]
    assert "result[error]>" not in success_lines[0]


def test_thinking_block_is_not_rendered():
    """An assistant's `thinking` block never reaches the transcript (private reasoning).

    Positive control on the same record: its `text` block *does* render, so
    this proves `thinking` was specifically excluded rather than the whole
    record being dropped.
    """
    record = {
        "type": "assistant",
        "sessionId": "fixture-synth",
        "message": {
            "role": "assistant",
            "content": [
                {"type": "thinking", "thinking": "invented private reasoning for this test"},
                {"type": "text", "text": "invented visible reply for this test"},
            ],
        },
    }

    output = normalize_records([record])

    assert "invented private reasoning" not in output
    assert "invented visible reply" in output


def test_system_record_uses_adapter_derived_kind_name():
    """A `system` record's rendered kind comes from the adapter's own subtype table.

    Asserts equality against `SYSTEM_SUBTYPE_KINDS` itself (imported, not
    restated), so this fails if the two ever drift instead of silently
    agreeing with a hand-copied duplicate. The unmapped-subtype case is the
    negative control: it must fall back to the generic `system` kind rather
    than crashing or inventing a name.
    """
    known = {
        "type": "system",
        "subtype": "compact_boundary",
        "sessionId": "fixture-synth",
        "content": "invented compaction note for this test",
    }
    unknown = {
        "type": "system",
        "subtype": "some_future_subtype_not_yet_classified",
        "sessionId": "fixture-synth",
        "content": "invented future-system note for this test",
    }

    output = normalize_records([known, unknown])

    expected_kind = SYSTEM_SUBTYPE_KINDS["compact_boundary"]
    known_lines = _lines_containing(output, "invented compaction note")
    assert len(known_lines) == 1
    assert f"SYSTEM({expected_kind}):" in known_lines[0]

    unknown_lines = _lines_containing(output, "invented future-system note")
    assert len(unknown_lines) == 1
    assert "SYSTEM(system):" in unknown_lines[0]


def test_bookkeeping_record_types_render_nothing():
    """Non-conversational bookkeeping record types contribute no output lines.

    Positive control: a `user` record in the same input does render, so this
    proves the bookkeeping types were specifically excluded rather than the
    whole input being silently dropped.
    """
    records = [
        {"type": "ai-title", "sessionId": "fixture-synth", "title": "invented title"},
        {"type": "mode", "sessionId": "fixture-synth", "mode": "default"},
        {"type": "attachment", "sessionId": "fixture-synth"},
        _user_record("invented message that should render for this test"),
    ]

    output = normalize_records(records)

    assert "invented title" not in output
    assert "invented message that should render" in output


# =============================================================================
# Robustness: a corrupt line does not fail the whole normalization
# =============================================================================


def test_malformed_json_line_is_skipped_not_fatal(tmp_path, caplog):
    """A corrupt JSONL line is logged and skipped; every well-formed record around it still renders.

    Positive control: the good records before and after the corrupt line
    both appear in the output, so this proves the corrupt line was skipped
    in place rather than truncating the rest of the file.
    """
    path = tmp_path / "corrupt.jsonl"
    _write_jsonl(
        path,
        [
            _user_record("invented message before the corrupt line"),
            b"{not valid json at all\n",
            _user_record("invented message after the corrupt line"),
        ],
    )

    with caplog.at_level(logging.WARNING):
        output = normalize_path(path)

    assert "invented message before the corrupt line" in output
    assert "invented message after the corrupt line" in output
    assert any("Unparseable" in record.message for record in caplog.records)


# =============================================================================
# Clipping: long text is bounded, not silently truncated
# =============================================================================


def test_long_text_is_clipped_with_elision_marker():
    """Text over the per-block cap is truncated with an explicit `…[+N chars]` marker.

    Positive control: a short text on a sibling record in the same input is
    rendered in full, unmarked — proving the cap applies to long text
    specifically, not to every line regardless of length.
    """
    long_text = "y" * 5000
    short_text = "invented short reply for this test"
    records = [_assistant_text_record(long_text), _assistant_text_record(short_text)]

    output = normalize_records(records)

    assert "…[+" in output
    assert "chars]" in output
    assert short_text in output
    short_line = _lines_containing(output, short_text)[0]
    assert "…[+" not in short_line


# =============================================================================
# INV-2 discipline: this module never opens a source file directly
# =============================================================================


def _direct_open_call_lines(path: Path) -> list[int]:
    """Line numbers of direct `open(...)` or `os.open(...)` calls in `path`."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    hits = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        if isinstance(func, ast.Name) and func.id == "open":
            hits.append(node.lineno)
        elif (
            isinstance(func, ast.Attribute)
            and func.attr == "open"
            and isinstance(func.value, ast.Name)
            and func.value.id == "os"
        ):
            hits.append(node.lineno)
    return hits


def test_normalize_module_never_opens_a_file_directly(tmp_path):
    """`palaver/extract/normalize.py` reads only through `read_complete_records`
    (in turn, `open_source_readonly`) — no bare `open()`/`os.open()` call.

    Mirrors `tests/test_invariants.py::test_adapters_route_every_read_through_the_chokepoint`'s
    detector for the same discipline applied outside `palaver/ingest/adapters/`.
    Positive control: the identical detector run against a poisoned module
    that does call `open()` directly finds it, proving the detector is live
    rather than vacuously clean.
    """
    assert NORMALIZE_MODULE_PATH.exists()
    assert _direct_open_call_lines(NORMALIZE_MODULE_PATH) == []

    poisoned = tmp_path / "poisoned_normalize.py"
    poisoned.write_text("def read_it(path):\n    with open(path) as f:\n        return f.read()\n")
    assert _direct_open_call_lines(poisoned) == [2]
